name: Install Prerequisites on Ubuntu

runs:
  using: composite
  steps:
    - name: Install packages
      run: |
        sudo apt-get update -q
        sudo apt-get install -yq \
            libboost-dev \
            libgdal-dev \
            libgeos++-dev
      shell: bash

